"""End-to-end project assembly.

After the generator emits one file per node, `assemble()` produces the three
final artifacts that turn a folder of Python files into a *runnable project*:

* `requirements.txt` — derived deterministically from the AST of every
  generated file. Sibling imports and standard-library modules are filtered
  out; only third-party roots remain.
* `README.md` — derived deterministically from the Quinny project's own
  `goal` fields. No Claude call.
* `main.py` — generated by Claude, given every source file as context, with
  the job of wiring the top-level tasks together into a demo entry point.

The two deterministic files always succeed. `main.py` is best-effort; if
Claude produces something that doesn't compile, we fall back to a tiny
import-only stub so the project still runs.
"""

from __future__ import annotations

import ast
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import anthropic

from quinny._capabilities import thinking_kwargs, make_client
from quinny.generator import GeneratedFile, GenerationResult, _strip_fences
from quinny.nodes import Component, Project, Task
from quinny.usage import UsageTracker


class AssembleError(Exception):
    pass


@dataclass
class AssemblyResult:
    main_py: str
    requirements_txt: str
    readme_md: str

    def write(self, out_dir: Path) -> None:
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "main.py").write_text(self.main_py)
        (out_dir / "requirements.txt").write_text(self.requirements_txt)
        (out_dir / "README.md").write_text(self.readme_md)


# --------------------------- requirements.txt ---------------------------

# Python 3.10+ ships `sys.stdlib_module_names`; older versions don't.
_STDLIB: set[str] = set(getattr(sys, "stdlib_module_names", set())) | {
    "__future__", "typing_extensions",
}


def derive_requirements(generation: GenerationResult) -> str:
    """Walk every generated .py file's AST, collect third-party import roots."""
    generated_modules = {
        f.filename[:-3] for f in generation.files if f.filename.endswith(".py")
    }
    third_party: set[str] = set()
    for f in generation.files:
        if not f.filename.endswith(".py"):
            continue
        try:
            tree = ast.parse(f.source)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    _maybe_add(alias.name, third_party, generated_modules)
            elif isinstance(node, ast.ImportFrom):
                # `from . import X` or `from .foo` — level > 0 means relative.
                if node.level == 0 and node.module:
                    _maybe_add(node.module, third_party, generated_modules)
    if not third_party:
        return "# No third-party dependencies detected.\n"
    return "\n".join(sorted(third_party)) + "\n"


def _maybe_add(dotted: str, dest: set[str], generated: set[str]) -> None:
    root = dotted.split(".")[0]
    if root and root not in _STDLIB and root not in generated:
        dest.add(root)


# ------------------------------ README.md -------------------------------

def derive_readme(project: Project, generation: GenerationResult) -> str:
    """A human-readable README from the Quinny spec + generated file list."""
    lines: list[str] = [f"# {project.name}", ""]
    lines.append("Generated by [Quinny](https://github.com/) — a task-oriented ")
    lines.append("intent language for AI coding agents.")
    lines.append("")
    lines.append("## Run")
    lines.append("")
    lines.append("```bash")
    lines.append("pip install -r requirements.txt")
    lines.append("python main.py")
    lines.append("```")
    lines.append("")
    lines.append("## Task graph")
    lines.append("")

    file_by_name = {f.name: f for f in generation.files}
    for decl in project.declarations:
        kind = "task" if isinstance(decl, Task) else "component"
        f = file_by_name.get(decl.name)
        fname = f.filename if f else "—"
        goal = decl.goal.lines[0] if decl.goal and decl.goal.lines else ""
        lines.append(f"### `{fname}` — {kind} `{decl.name}`")
        lines.append("")
        if goal:
            lines.append(f"**Goal.** {goal}")
            lines.append("")
        if isinstance(decl, Task) and decl.depends:
            lines.append(f"**Depends on:** {', '.join(decl.depends)}")
            lines.append("")
        if isinstance(decl, Component) and decl.uses:
            lines.append(f"**Uses:** {', '.join(decl.uses)}")
            lines.append("")
    return "\n".join(lines) + "\n"


# ------------------------------ main.py ---------------------------------

_MAIN_SYSTEM_PROMPT = """You are assembling a Python project from generated \
modules. Emit a single main.py that wires them together into a demo.

Rules:
1. Output ONLY main.py source. No prose, no markdown fences, no explanations.
2. Use `if __name__ == "__main__":` for the entry point.
3. Import from the generated modules by their filenames (e.g. `from login \
import authenticate`).
4. Call the top-level tasks in a plausible order to demonstrate the flow.
5. Use dummy inputs where needed. Don't require env vars or external services.
6. Keep it short — a runnable demo, not a production driver."""


def _generate_main(
    project: Project,
    generation: GenerationResult,
    client: anthropic.Anthropic,
    model: str,
    max_tokens: int,
    tracker: "UsageTracker | None" = None,
) -> str:
    # Cap per-file source in the context to keep the prompt small.
    parts: list[str] = []
    for f in generation.files:
        snippet = f.source if len(f.source) < 1500 else f.source[:1500] + "\n# ..."
        parts.append(f"### {f.filename}\n```python\n{snippet}\n```")
    files_block = "\n\n".join(parts)

    user_msg = (
        f"Project: {project.name}\n\n"
        f"Generated modules:\n\n{files_block}\n\n"
        f"Emit main.py that ties everything together into a working demo."
    )

    response = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=_MAIN_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_msg}],
        **thinking_kwargs(model),
    )
    if tracker is not None:
        tracker.record("assemble", model, response)
    raw = "\n".join(
        b.text for b in response.content if getattr(b, "type", None) == "text"
    )
    return _strip_fences(raw)


def _fallback_main(generation: GenerationResult) -> str:
    """Import-only stub used when the model's main.py doesn't compile."""
    imports = "\n".join(
        f"import {f.filename[:-3]}"
        for f in generation.files if f.filename.endswith(".py")
    )
    return (
        '"""Auto-generated fallback main.py.\n\n'
        'Claude\'s generated main.py failed to compile — this stub just\n'
        'imports every module so `python main.py` at least verifies that\n'
        'the project is importable end-to-end.\n"""\n\n'
        f"{imports}\n\n"
        'if __name__ == "__main__":\n'
        '    print("All modules imported successfully.")\n'
    )


def _trial_run_main(main_source: str, generation: GenerationResult) -> tuple[bool, str]:
    """Write main + every generated file into a temp dir and try `python main.py`.

    Returns (success, stderr). Used by the assembly repair loop to catch
    the common failure modes — wrong import name, wrong function signature,
    missing symbol — before we hand the project to the user.
    """
    with tempfile.TemporaryDirectory(prefix="quinny_main_trial_") as tmp:
        tmp_path = Path(tmp)
        for f in generation.files:
            (tmp_path / f.filename).write_text(f.source + "\n")
        main_path = tmp_path / "main.py"
        main_path.write_text(main_source)
        env = os.environ.copy()
        env["PYTHONPATH"] = str(tmp_path) + os.pathsep + env.get("PYTHONPATH", "")
        try:
            r = subprocess.run(
                [sys.executable, str(main_path.resolve())],
                cwd=str(tmp_path), env=env,
                capture_output=True, text=True, timeout=20,
            )
        except subprocess.TimeoutExpired:
            return False, "Trial run timed out after 20s."
        if r.returncode == 0:
            return True, ""
        return False, (r.stderr or r.stdout or f"exit code {r.returncode}").strip()


def _repair_main(
    project: Project,
    generation: GenerationResult,
    current: str,
    error_log: str,
    client: anthropic.Anthropic,
    model: str,
    max_tokens: int,
    tracker: "UsageTracker | None" = None,
) -> str:
    """Ask Claude to fix a failing main.py, given the trial-run error."""
    parts: list[str] = []
    for f in generation.files:
        snippet = f.source if len(f.source) < 1500 else f.source[:1500] + "\n# ..."
        parts.append(f"### {f.filename}\n```python\n{snippet}\n```")
    files_block = "\n\n".join(parts)

    user_msg = (
        f"Project: {project.name}\n\n"
        f"Generated modules:\n\n{files_block}\n\n"
        f"Your previous main.py:\n```python\n{current}\n```\n\n"
        f"Running `python main.py` failed with:\n```\n{error_log}\n```\n\n"
        f"Rewrite main.py so this error goes away. Output only main.py source."
    )
    response = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=_MAIN_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_msg}],
        **thinking_kwargs(model),
    )
    if tracker is not None:
        tracker.record("assemble", model, response)
    raw = "\n".join(
        b.text for b in response.content if getattr(b, "type", None) == "text"
    )
    return _strip_fences(raw)


# ------------------------------- top level ------------------------------

def assemble(
    project: Project,
    generation: GenerationResult,
    *,
    client: anthropic.Anthropic | None = None,
    model: str = "claude-opus-4-7",
    max_tokens: int = 4096,
    tracker: "UsageTracker | None" = None,
    max_main_repair: int = 2,
) -> AssemblyResult:
    """Produce main.py + requirements.txt + README.md for a generated project.

    After Claude emits main.py, we do a *trial run* in an isolated temp dir
    with the generated modules on PYTHONPATH. On failure (import error,
    signature mismatch, runtime bug) we feed the traceback back to Claude
    and ask for a corrected main.py. Up to `max_main_repair` retries.
    Falls back to the import-only stub if all repairs fail.
    """
    if generation.target != "python":
        raise AssembleError(
            f"Assembly for target '{generation.target}' not implemented yet."
        )
    if client is None:
        if not (os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN")):
            raise AssembleError("ANTHROPIC_API_KEY is not set.")
        client = make_client()

    reqs = derive_requirements(generation)
    readme = derive_readme(project, generation)
    main = _generate_main(project, generation, client, model, max_tokens,
                          tracker=tracker)

    # 1. Syntax-fallback: if the raw main.py won't even compile, don't
    #    bother trial-running it — go straight to the import-only stub.
    try:
        compile(main, "main.py", "exec")
    except SyntaxError:
        main = _fallback_main(generation)
        return AssemblyResult(main_py=main, requirements_txt=reqs, readme_md=readme)

    # 2. Trial-run + repair loop: catches wrong imports, missing symbols,
    #    signature mismatches, and other runtime failures.
    for _attempt in range(max_main_repair + 1):
        ok, err = _trial_run_main(main, generation)
        if ok:
            break
        if _attempt == max_main_repair:
            main = _fallback_main(generation)  # give up; ship the safe stub
            break
        main = _repair_main(
            project, generation, main, err,
            client, model, max_tokens, tracker=tracker,
        )
        # If a repair round produced garbage that doesn't compile, stop.
        try:
            compile(main, "main.py", "exec")
        except SyntaxError:
            main = _fallback_main(generation)
            break

    return AssemblyResult(main_py=main, requirements_txt=reqs, readme_md=readme)
